# Generated by Django 4.1.10 on 2023-08-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
    ]
